- name: Bazel Action
  # You may pin to the exact commit or the version.
  # uses: ngalaiko/bazel-action@ad5c8499ac2945bb7cc56587ed9da4a96b4fbb84
  uses: ngalaiko/bazel-action@2.0.0
  with:
    # Arguments to the bazel command
    args: run mpce
